### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by funkekaiser**
Please dont hide the real guide in the issues tab.
Also added the real path to the config file

### CODE REVIEW

**Comment by jammsen** [comment]
> Please dont hide the real guide in the issues tab. 

What are you meaning? I dont hide anything, 
Everything is free to see for all, thats why it is on Github?!

**Comment by funkekaiser** [comment]
I just think the "good" guide should be on the frontpage/README, I did not mean to accuse you of intentionally hiding it :) Once the issue is resolved the directions will be buried in tickets.

**Comment by jammsen** [comment]
How about you read #33 and help out, i already confirmed we can together make things better ... why assume the something worse from me ... when you dont know me 😞

**Comment by funkekaiser** [comment]
#33 is the reason I am here. I don't know why you are so defensive. I opened this fork so we can work on a better version.

**Comment by jammsen** [comment]
First you accuse me of hiding things, then you go ahead and say knowledge will be burried in issues, now im to defensive ... how about you stop trying to tell me how to be and how to life my life and reflect on yourself and try to be less invasive and just a little bit respectful with people you dont know .... If thats your way of helping ... giving a little and full of assumptions, i would rather not have it ... no one ever didnt say you couldnt ask a question, to get an answer but i dont see that here ... to be honest, right now reading your text i feel like im beeing the one thats an asshole for not doing things your way .... i dont need that!

Again i said try to help by reading first #33 because there its stated we want to try out to go with a wiki, but you just send me a commit with changes that dont reflect what we wanted to do ...

**Comment by funkekaiser** [comment]
go get some professional help

**Pull request closed without merging**
