### PR TITLE
Fixed spelling and grammar in ISSUE_TEMPLATE

### PR DESCRIPTION
**Pull request by JS-E**
Just a few fixes to spelling and grammar i noticed in the ISSUE_TEMPLATE

### CODE REVIEW

**Comment by jammsen** [comment]
Hey @JS-E im confused a bit, Github asks me to accept the pull-request of 2 users with 2 commits, but i only see 1 change really and 1 verified real account here, who is the other? Am i stupid and imagine stuff here? Im confused can you clear things up?

image

**Comment by JS-E** [comment]
Ahh right, i committed this from my IDE which put my name into the commit, then when i attached it to my github user it applied my github name with it. Both commits are from me but i think i've managed to confuse github. My bad 😆

**Comment by jammsen** [comment]
> Ahh right, i committed this from my IDE which put my name into the commit, then when i attached it to my github user it applied my github name with it. Both commits are from me but i think i've managed to confuse github. My bad 😆

Well yeah, you confused me too😖 😃 
Okay thanks for clearing this up, im happy im not stupid, gotcha thanks 😎

**Review by jammsen — APPROVED** [review]
Thanks for your contribution!

**Pull request merged**
